# Generated by Django 4.2.2 on 2023-10-19 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default=None, max_length=264)),
                ('bio_image_url', models.CharField(default=None, max_length=264)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
